<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SMS\Student;
use Carbon\Carbon;

class SMSStudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'student_id' => 'NS-2024-0001',
                'rank' => 'Private',
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'name_in_dhivehi' => 'އަހްމަދު ހަސަން',
                'email' => 'ahmed.hassan@example.com',
                'national_id' => 'A1234567',
                'permanent_address_name' => 'House No. 15',
                'permanent_atoll' => 'Malé',
                'permanent_island' => 'Malé',
                'permanent_district' => 'Henveiru',
                'permanent_road_name' => 'Ameer Ahmed Magu',
                'present_address_name' => 'House No. 15',
                'present_atoll' => 'Malé',
                'present_island' => 'Malé',
                'present_district' => 'Henveiru',
                'present_road_name' => 'Ameer Ahmed Magu',
                'contact_no' => '+960 1234567',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'date_of_birth' => '2000-05-15',
                'service_duration' => '2 years',
                'parent_name' => 'Hassan Ali',
                'parent_relationship' => 'Father',
                'parent_email' => 'hassan.ali@example.com',
                'parent_contact_no' => '+960 7654321',
                'parent_address' => 'Same as above',
                'batch_id' => 1,
                'company' => 'Alpha Company',
                'platoon' => '1st Platoon',
                'date_of_joining' => '2024-01-15',
                'application_date' => '2024-01-01',
                'applicant_number' => 'APP-001',
                'pay_amount' => 5000.00,
                'status' => 'active',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 'NS-2024-0002',
                'rank' => 'Private',
                'first_name' => 'Aisha',
                'last_name' => 'Mohamed',
                'name_in_dhivehi' => 'އައިޝާ މުހައްމަދު',
                'email' => 'aisha.mohamed@example.com',
                'national_id' => 'A2345678',
                'permanent_address_name' => 'House No. 25',
                'permanent_atoll' => 'Malé',
                'permanent_island' => 'Malé',
                'permanent_district' => 'Machangolhi',
                'permanent_road_name' => 'Majeedhee Magu',
                'present_address_name' => 'House No. 25',
                'present_atoll' => 'Malé',
                'present_island' => 'Malé',
                'present_district' => 'Machangolhi',
                'present_road_name' => 'Majeedhee Magu',
                'contact_no' => '+960 2345678',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'date_of_birth' => '2001-08-22',
                'service_duration' => '2 years',
                'parent_name' => 'Mohamed Ali',
                'parent_relationship' => 'Father',
                'parent_email' => 'mohamed.ali@example.com',
                'parent_contact_no' => '+960 8765432',
                'parent_address' => 'Same as above',
                'batch_id' => 1,
                'company' => 'Beta Company',
                'platoon' => '2nd Platoon',
                'date_of_joining' => '2024-01-15',
                'application_date' => '2024-01-01',
                'applicant_number' => 'APP-002',
                'pay_amount' => 5000.00,
                'status' => 'active',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 'NS-2024-0003',
                'rank' => 'Private',
                'first_name' => 'Ibrahim',
                'last_name' => 'Ali',
                'name_in_dhivehi' => 'އިބްރާހިމް ޢަލީ',
                'email' => 'ibrahim.ali@example.com',
                'national_id' => 'A3456789',
                'permanent_address_name' => 'House No. 35',
                'permanent_atoll' => 'Malé',
                'permanent_island' => 'Malé',
                'permanent_district' => 'Galolhu',
                'permanent_road_name' => 'Boduthakurufaanu Magu',
                'present_address_name' => 'House No. 35',
                'present_atoll' => 'Malé',
                'present_island' => 'Malé',
                'present_district' => 'Galolhu',
                'present_road_name' => 'Boduthakurufaanu Magu',
                'contact_no' => '+960 3456789',
                'gender' => 'Male',
                'blood_group' => 'B+',
                'date_of_birth' => '1999-12-10',
                'service_duration' => '2 years',
                'parent_name' => 'Ali Hassan',
                'parent_relationship' => 'Father',
                'parent_email' => 'ali.hassan@example.com',
                'parent_contact_no' => '+960 9876543',
                'parent_address' => 'Same as above',
                'batch_id' => 1,
                'company' => 'Gamma Company',
                'platoon' => '3rd Platoon',
                'date_of_joining' => '2024-01-15',
                'application_date' => '2024-01-01',
                'applicant_number' => 'APP-003',
                'pay_amount' => 5000.00,
                'status' => 'active',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($students as $studentData) {
            Student::create($studentData);
        }
    }
}
